site_name: mapper
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: mappertec/mapper
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.tabs
plugins:
  - blog
markdown_extensions:
  - attr_list