cd ./terraform/cognito
terraform init
terraform plan
terraform apply --auto-approve

$user_pool_id = $(terraform output -raw user_pool_id)
$client_id = $(terraform output -raw client_id)
$identity_pool_id = $(terraform output -raw identity_pool_id)

$outFile="..\..\frontend\.env"
$region="eu-west-2"
"# DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED BY RUNNING create_cognito.ps1" | Out-File $outFile -encoding ASCII
("REACT_APP_USER_POOL_ID=" + $user_pool_id) | Out-File $outFile -encoding ASCII -append
("REACT_APP_CLIENT_ID=" + $client_id) | Out-File $outFile -encoding ASCII -append
("REACT_APP_REGION=" + $region) | Out-File $outFile -encoding ASCII -append
("REACT_APP_COGNITO_ID=cognito-idp." + $region + ".amazonaws.com/" + $user_pool_id) | Out-File $outFile -encoding ASCII -append
("REACT_APP_IDENTITY_POOL=" + $identity_pool_id) | Out-File $outFile -encoding ASCII -append

cd ../..