name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        run: ./gradlew :shadowJar
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy on AWS
        run: |
          ls -l ./build/libs
          aws lambda update-function-code --function-name service1 --zip-file "fileb://./build/libs/service1-1.0-SNAPSHOT-all.jar"
#  deploy:
#    runs-on: ubuntu-latest
#    env:
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
#      AWS_DEFAULT_OUTPUT: json
#    steps:
#      - uses: actions/checkout@v2
#      - name: Deploy
#        run: ./scripts/amplify-deploy.sh db6n4xmnpgppq master